site_name: Object Oriented Programming OOP IEC61131-3 Youtube Course by Runtimevic
docs_dir: '../../docs/en'
site_url: https://runtimevic.github.io/OOP-IEC61131-3--Curso-Youtube/
site_author: runtimevic
site_description: IEC 61131-3 PLC OOP Course

# Repository
repo_name: runtimevic/OOP-IEC61131-3--Curso-Youtube
repo_url: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
edit_uri: ""

theme:
  name: material
#  logo: imagenes/OOP_Logo2.png
  custom_dir: overrides
  logo: imagenes/oop_logg.webp
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  features:
#    - navigation.tabs        
  language: en
  features:
    - navigation.footer
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16    

# Plugins
plugins:
  - search:
      lang: en
  - with-pdf:
      copyright: Copyright &copy; 2023 Víctor Durán.
      cover_subtitle: Object Oriented Programming OOP IEC61131-3 PLC Youtube Course by Runtimevic.
      output_path: ../document-en.pdf
  - pdf-export:
      combined: true
               
# Customization
extra:
  analytics:
    provider: google
    property: G-42EY64EE3Z
  consent:
    title: Cookie consent
    description: >- 
      Utilizamos cookies para reconocer sus visitas repetidas y preferencias, así como
      como para medir la eficacia de nuestra documentación y si los usuarios
      encuentran lo que están buscando. Con su consentimiento, nos está ayudando a
      mejorar nuestra documentación.
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.    
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913/
    - icon: fontawesome/brands/github
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:victorduranm@hotmail.com
    - icon: fontawesome/regular/file-pdf
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube/blob/gh-pages/document-en.pdf
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/playlist?list=PLEfi_hUmmSjFpfdJ6yw3B9yj7dWHYkHmQ         
  version:
    provider: mike
  alternate:
    - name: English
      link: /OOP-IEC61131-3--Curso-Youtube/en/
      lang: en
    - name: Spanish
      link: /OOP-IEC61131-3--Curso-Youtube/es/
      lang: es
    - name: Italian
      link: /OOP-IEC61131-3--Curso-Youtube/it/
      lang: it
    - name: Portuguese
      link: /OOP-IEC61131-3--Curso-Youtube/pt/
      lang: pt
  #disqus: 'OOP IEC-61131-3 PLC'        

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true      
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde   
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta          

nav:
    - Requeriments: requeriments.md
    - Introduction: index.md
    - Types of paradigms: Types of Paradigms.md
    - Concepts Previous:
      - Type of Data: Concepts Previous/Tipos de datos.md       
      - Variable types and special variables: Concepts Previous/Variable types and special variables.md
      - Access modifiers: Concepts Previous/access modifiers.md
      - Access Modifiers Table: Concepts Previous/Tabla de Modificadores de acceso.md   
    - Classes and Objects:
      - Classes and Objects: Clases y Objetos/clases y objetos.md
      - Function Block: 
          - Function Block: Clases y Objetos/Function Block.md
          - Function Block Access Modifiers:  Clases y Objetos/Function Block Modificadores de acceso.md
          - Function Block Declaration variables: Clases y Objetos/Function Block Declaracion de variables.md
          - Constructor and Destructor: Clases y Objetos/Constructor y Destructor.md          
      - Object Method:
          - Method: Clases y Objetos/metodo.md
          - Method access modifiers: Clases y Objetos/Metodo Modificadores de acceso.md
          - Method Declaration of variables: Clases y Objetos/Metodo Declaracion de variables.md
          - Method return variable types: Clases y Objetos/Metodo Tipos de variables de retorno.md      
      - Object Property: Clases y Objetos/propiedad.md
      - Inheritance:
          - Inheritance Function Block: Clases y Objetos/Inheritance/Inheritance Function Block.md
          - Inheritance Structure: Clases y Objetos/Inheritance/Inheritance Structure.md
          - Inheritance Interface: Clases y Objetos/Inheritance/Inheritance Interface.md
      - THIS pointer: Clases y Objetos/THIS pointer.md
      - SUPER pointer: Clases y Objetos/SUPER pointer.md    
      - Interface: Clases y Objetos/interface.md
      - pointer and reference: Clases y Objetos/pointer and reference.md
      - Keyword Abstract: Clases y Objetos/Keyword_Abstract.md
      - Abstract FB vs Interface: Clases y Objetos/FB abstracto frente a interfaz.md
      - Fluent Interface: Clases y Objetos/Interfaz fluida.md
      - Interface vs Inheritance: Clases y Objetos/Interface vs Inheritance.md
      - Further operators: Clases y Objetos/Further operators.md
    - ExST:
      - Extended Structured Text: Extended_Structured_Text.md   
    - OOP Principles: 
      - 4 Pillars: principios/_principios OOP.md
      - Abstraction: principios/abstraccion.md
      - Encapsulation: principios/encapsulamiento.md
      - Inheritance: principios/herencia.md
      - Polymorphism: principios/polimorfismo.md    
    - SOLID: 
      - SOLID: solid/_SOLID.md
      - SRP - Single Responsibility Principle: solid/Principio de Responsabilidad Única.md
      - OCP - Open/Closed Principle: solid/Principio de Abierto_Cerrado.md
      - LSP - Liskov Substitution Principle: solid/Principio de Sustitución de Liskov.md
      - ISP - Interface Segregation Principle: solid/Principio de Segregación de Interfaz.md
      - DIP - Dependency Inversion Principle: solid/Principio de Inversión de Dependencia.md
    - UML: 
      - UML: UML/UML.md
      - Class UML: UML/Class UML.md
      - Relations: UML/relations.md
      - StateChart UML: UML/Statechart UML.md
    - Types of Design for PLC programming: Types of Design for PLC programming.md
    - Design patterns:
      - Design patterns: Patrones de Diseño/_Patrones de Diseño.md
      - Strategy Pattern: Patrones de Diseño/Strategy pattern.md
      - The Abstract Factory Pattern: Patrones de Diseño/The Abstract Factory Pattern.md
      - The Visitor Design Pattern: Patrones de Diseño/The Visitor Design Pattern.md
    - Libraries : Libraries.md
    - Links OOP: links.md
    - TDD:
      - TDD - Test Drive Development: TDD/Test Driven Development.md
      - Units Test: TDD/Unit Test.md