site_name: Programación Orientada a Objetos OOP IEC61131-3 Curso Youtube by Runtimevic
docs_dir: '../../docs/es'
site_url: https://runtimevic.github.io/OOP-IEC61131-3--Curso-Youtube/es/
site_author: runtimevic
site_description: Curso OOP 61131-3 PLC

# Repository
repo_name: runtimevic/OOP-IEC61131-3--Curso-Youtube
repo_url: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
edit_uri: ""

theme:
  name: material
#  logo: imagenes/OOP_Logo2.png
  custom_dir: overrides
  logo: imagenes/oop_logg.webp
  palette:
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  features:
#    - navigation.tabs        
  language: es
  features:
    - navigation.footer
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16    

# Plugins
plugins:
  - search:
      lang: es
  - with-pdf:
      copyright: Copyright &copy; 2023 Víctor Durán.
      cover_subtitle: Programación Orientada a Objetos OOP IEC61131-3 PLC Curso Youtube by Runtimevic.
      output_path: ../document-es.pdf
  - pdf-export:
      combined: true
  # - git-committers:
  #     repository: 'runtimevic/OOP-IEC61131-3--Curso-Youtube'
  #     docs_path: '../docs/es'
  - git-revision-date-localized:
      enable_creation_date: true                 
      type: datetime    
  # - git-authors

# Customization
extra:
  analytics:
    provider: google
    property: G-42EY64EE3Z
  consent:
    title: Cookie consentimiento
    description: >- 
      Utilizamos cookies para reconocer sus visitas repetidas y preferencias, así como
      como para medir la eficacia de nuestra documentación y si los usuarios
      encuentran lo que están buscando. Con su consentimiento, nos está ayudando a
      mejorar nuestra documentación.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913/
    - icon: fontawesome/brands/github
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:victorduranm@hotmail.com
    - icon: fontawesome/regular/file-pdf
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube/blob/gh-pages/document-es.pdf
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/playlist?list=PLEfi_hUmmSjFpfdJ6yw3B9yj7dWHYkHmQ       
  version:
    provider: mike
  alternate:
    - name: English
      link: /OOP-IEC61131-3--Curso-Youtube/en/
      lang: en
    - name: Español
      link: /OOP-IEC61131-3--Curso-Youtube/es/
      lang: es
    - name: Italiano
      link: /OOP-IEC61131-3--Curso-Youtube/it/
      lang: it
    - name: Portugues
      link: /OOP-IEC61131-3--Curso-Youtube/pt/
      lang: pt

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true      
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde   
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta     
  
nav:
    - Requisitos: requisitos.md
    - Introduccion: index.md
    - Tipos de paradigmas: tipos de paradigmas.md
    - Conceptos Previos:
       - Tipos de Datos: Conceptos Previos/Tipos de datos.md       
       - Tipos de variables y variables especiales: Conceptos Previos/Variable types and special variables.md
       - Modificadores de acceso: Conceptos Previos/modificadores de acceso.md
       - Tabla de Modificadores de acceso: Conceptos Previos/Tabla de Modificadores de acceso.md      
    - Clases y Objetos:
       - Clases y Objetos: Clases y Objetos/clases y objetos.md
       - Bloque de Funciones: 
          - Bloques de Funciones: Clases y Objetos/Function Block.md
          - Bloque de Funcion Modificadores de acceso:  Clases y Objetos/Function Block Modificadores de acceso.md
          - Bloque de Funcion Declaracion de variables: Clases y Objetos/Function Block Declaracion de variables.md
          - Constructor y Destructor: Clases y Objetos/Constructor y Destructor.md          
       - Objeto Metodo: 
          - Metodo: Clases y Objetos/metodo.md
          - Metodo Modificadores de acceso: Clases y Objetos/Metodo Modificadores de acceso.md
          - Metodo Declaracion de variables: Clases y Objetos/Metodo Declaracion de variables.md
          - Metodo tipos de variables de retorno: Clases y Objetos/Metodo Tipos de variables de retorno.md
       - Objeto Propiedad: Clases y Objetos/propiedad.md
       - Herencia:
          - Herencia Bloque de Funcion: Clases y Objetos/Herencia/Herencia Bloque de Funcion.md
          - Herencia Estructura: Clases y Objetos/Herencia/Herencia Estructura.md
          - Herencia Interface: Clases y Objetos/Herencia/Herencia Interface.md
       - THIS puntero: Clases y Objetos/THIS pointer.md
       - SUPER puntero: Clases y Objetos/SUPER pointer.md
       - Interface: Clases y Objetos/interface.md
       - puntero y referencia: Clases y Objetos/pointer and reference.md
       - Palabra clave Abstracto: Clases y Objetos/Keyword_Abstract.md
       - FB Abstracto vs Interface: Clases y Objetos/FB abstracto frente a interfaz.md
       - Interface fluida: Clases y Objetos/Interfaz fluida.md
       - Interface vs Herencia: Clases y Objetos/Interface vs Herencia.md
       - Otros Operadores: Clases y Objetos/Otros Operadores.md
    - ExST:
       - Texto Estructurado Extendido: Extended_Structured_Text.md
    - Principios OOP: 
       - 4 Pilares: principios/_principios OOP.md
       - Abstracción: principios/abstraccion.md
       - Encapsulamiento: principios/encapsulamiento.md
       - Herencia: principios/herencia.md
       - Polimorfismo: principios/polimorfismo.md    
    - SOLID: 
       - SOLID: solid/_SOLID.md
       - SRP - Principio de Responsabilidad Única: solid/Principio de Responsabilidad Unica.md
       - OCP - Principio de Abierto/Cerrado: solid/Principio de Abierto_Cerrado.md
       - LSP - Principio de Sustitución de Liskov: solid/Principio de Sustitucion de Liskov.md
       - ISP - Principio de Segregación de Interfaz: solid/Principio de Segregacion de Interfaz.md
       - DIP - Principio de Inversión de Dependencia: solid/Principio de Inversion de Dependencia.md
    - UML: 
       - UML: UML/UML.md
       - Class UML: UML/Class UML.md
       - Relaciones: UML/relaciones.md
       - StateChart UML: UML/Statechart UML.md
    - Tipos de Diseño para programacion OOP: Tipos de Diseño para programacion de PLC.md
    - Patrones de Diseño:
       - Patrones de Diseño : Patrones de Diseño/_Patrones de Diseño.md
       - Patrones de Diseño Creacional:
          - Patron Factory Method: Patrones de Diseño/Creational/Factory Method Design Pattern.md
          - Patron Abstract Factory: Patrones de Diseño/Creational/Abstract Factory Design Pattern.md
          - Patron Builder: Patrones de Diseño/Creational/Builder Design Pattern.md
          - Patron Prototype: Patrones de Diseño/Creational/Prototype Design Pattern.md
          - Patron Singleton: Patrones de Diseño/Creational/Singleton Design Pattern.md
       - Patrones de Diseño Estructural:
          - Patron Adapter: Patrones de Diseño/Structural/Adapter Design Pattern.md
          - Patron Bridge: Patrones de Diseño/Structural/Bridge Design Pattern.md
          - Patron Composite: Patrones de Diseño/Structural/Composite Design Pattern.md
          - Patron Decorator: Patrones de Diseño/Structural/Decorator Design Pattern.md
          - Patron Facade: Patrones de Diseño/Structural/Facade Design Pattern.md
          - Patron Flyweight: Patrones de Diseño/Structural/Flyweight Design Pattern.md
          - Patron Proxy: Patrones de Diseño/Structural/Proxy Design Pattern.md
       - Patrones de Diseño de Comportamiento:
          - Patron Chain of Responsibility: Patrones de Diseño/Behavioral/Chain of Responsibility Design Pattern.md
          - Patron Command: Patrones de Diseño/Behavioral/Command Design Pattern.md
          - Patron Iterator: Patrones de Diseño/Behavioral/Iterator Design Pattern.md
          - Patron Mediator: Patrones de Diseño/Behavioral/Mediator Design Pattern.md
          - Patron Memento: Patrones de Diseño/Behavioral/Memento Design Pattern.md
          - Patron Observer: Patrones de Diseño/Behavioral/Observer Design Pattern.md
          - Patron State: Patrones de Diseño/Behavioral/State Design Pattern.md
          - Patron Strategy: Patrones de Diseño/Behavioral/Strategy Design Pattern.md
          - Patron Template Method: Patrones de Diseño/Behavioral/Template Method Design Pattern.md
          - Patron Visitor: Patrones de Diseño/Behavioral/Visitor Design Pattern.md  
    - Librerias : Librerias.md
    - CI/CD:
       - CI/CD - Integración y entrega continua: CI_CD/Integracion y entrega continua.md
       - Git: CI_CD/Git.md
       - TDD:
          - TDD - Desarrollo guiado por pruebas: TDD/Test Driven Development.md
          - Pruebas Unitarias: TDD/Unit Test.md
          - Pruebas Integracion: TDD/Integration Test.md
       - Simulacion:
          - Simulacion: CI_CD/Simulacion.md
    - Links OOP: links.md    
 